del "ganja-auth-server\AUTH.db"
del "ganja-web-server\WEB.db"
del "ganja-cluster-server\CLUSTER-0.db"
del "ganja-cluster-server\CLUSTER-1.db"
del "ganja-cluster-server\CLUSTER-2.db"
del "ganja-file-server\CLUSTER-0.db"
rd /s /q "ganja-file-server\data\"