del "C:\Users\jcalc\Documents\ganja-file-system\ganja-auth-server\AUTH.db"
del "C:\Users\jcalc\Documents\ganja-file-system\ganja-web-server\WEB.db"
del "C:\Users\jcalc\Documents\ganja-file-system\ganja-cluster-server\CLUSTER-0.db"
del "C:\Users\jcalc\Documents\ganja-file-system\ganja-cluster-server\CLUSTER-1.db"
del "C:\Users\jcalc\Documents\ganja-file-system\ganja-cluster-server\CLUSTER-2.db"
del "C:\Users\jcalc\Documents\ganja-file-system\ganja-file-server\CLUSTER-0.db"
rd /s /q "C:\Users\jcalc\Documents\ganja-file-system\ganja-file-server\data\"