del "ganja-auth-server\AUTH.db"
del "ganja-web-server\WEB.db"
del "ganja-cluster-server\CLUSTER-0.db"
del "ganja-cluster-server\CLUSTER-1.db"
del "ganja-cluster-server\CLUSTER-2.db"
rd /s /q "ganja-file-server\data-0"
rd /s /q "ganja-file-server\data-1"
rd /s /q "ganja-file-server\data-2"
rd /s /q "ganja-file-server\data-3"
rd /s /q "ganja-file-server\data-4"
rd /s /q "ganja-file-server\data-5"
rd /s /q "ganja-file-server\data-6"
rd /s /q "ganja-file-server\data-7"

